name: Build and Deploy to dev
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          repository-name: TheCavern/wiki-dev.thecavern.net
          token: ${{ secrets.DEVDEPLOY_KEY }}